drop table if exists `person`;
drop table if exists `signalement`;
CREATE TABLE `person` (
  `ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `FIRSTNAME` VARCHAR(100) NOT NULL,
  `LASTNAME` VARCHAR(50) NOT NULL,
  `EMAIL` VARCHAR(50) NOT NULL,
  `ADRESS` VARCHAR(50) NOT NULL,
  `TEL` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;

CREATE TABLE `signalement` (
  `ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `IMPORTANCE` VARCHAR(100) NOT NULL,
  `OBJECT` VARCHAR(50) NOT NULL,
  `DESCRIPTION` VARCHAR(50) NOT NULL,
  `COMMENT` VARCHAR(50) NOT NULL,
  `PLACE` VARCHAR(50) NOT NULL,
  `IDPERSON` INT(10) NOT NULL,
  PRIMARY KEY (`ID`)
  ) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;
